-- AlterTable
ALTER TABLE "CotizacionItem" ALTER COLUMN "anchoCm" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "altoCm" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "VentaItem" ALTER COLUMN "anchoCm" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "altoCm" SET DATA TYPE DOUBLE PRECISION;
